version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_DB=platform_base
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - JWT_SECRET_KEY=your_jwt_secret
      - OPENAI_API_KEY=your_openai_api_key
      - LANGCHAIN_API_KEY=your_langchain_api_key
      - DRAMATIQ_BROKER_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
